### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "xeon2",
    "password": "xeon2"
}

### Login
GET  http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "xeon2",
    "password": "xeon2"
}

###
GET  http://localhost:3000/project/show
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inhlb24yIiwiaWF0IjoxNjM3MDUwNzU2fQ.eThQhIK-Qwm5jmzylqKr92eRwEUnpWCY3MT56r3etzQ

###
POST http://localhost:3000/project/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inhlb24yIiwiaWF0IjoxNjM2OTcxMDY1fQ._oavVsTmjEpwNjL4I6b10pKphEhjhjj6S-sY8_XUJvc

{
    "name": "backend in express js",
    "description": "Create a local server, and write some rest API",
    "startAt": "11/11/2021",
    "endAt": "11/12/2021"
}